export interface Member {
  name: string;
  course: string;
  year: string;
  position: string,
}

export const members: Member[] = [
  // { name: "PRATYUSH BAMETA", course: "B.TECH CSE", year: "2nd Year", position: "CHAIRPERSON" },
  // { name: "RIYA BHATT", course: "B.TECH CSE", year: "2nd Year", position: "VICE CHAIR" },
  // { name: "SAMRIDDHI GURURANI", course: "B.TECH CSE", year: "2nd Year", position: "SECRETARY" },
  // { name: "VARUN SINGH", course: "B.TECH CSE", year: "2nd Year", position: "TREASURER" },
  // { name: "YASH KARKI", course: "B.TECH CSE", year: "2nd Year", position: "WEBMASTER" },
  // { name: "HEMANT GOSWAMI", course: "B.TECH ECE", year: "2nd Year", position: "TECHNICAL / PROJECT HEAD" },
  // { name: "VANSHIKA CHAUHAN", course: "BCA", year: "2nd Year", position: "TECHNICAL / PROJECT HEAD" },
  // { name: "ARYAN TIWARI", course: "B.TECH CSE", year: "1st Year", position: "TECHNICAL / PROJECT" },
  // { name: "KHUSHBU KANYAL", course: "B.TECH CSE", year: "2nd Year", position: "TECHNICAL / PROJECT" },
  // { name: "SAMARTH JOHRI", course: "B.TECH CSE", year: "2nd Year", position: "EVENT COORDINATOR HEAD" },
  // { name: "HIMANSHI KARAKOTI", course: "B.TECH CSE", year: "2nd Year", position: "EVENT COORDINATOR HEAD" },
  // { name: "NIRAJ SINGH BISHT", course: "B.TECH ECE", year: "2nd Year", position: "EVENT COORDINATOR" },
  // { name: "SMITI SINGH", course: "B.TECH CSE", year: "2nd Year", position: "EVENT COORDINATOR" },
  // { name: "HARSH MAURYA", course: "B.TECH CSE", year: "1st Year", position: "EVENT COORDINATOR" },
  // { name: "PRIYANKA GANGWAR", course: "B.TECH CSE", year: "1st Year", position: "EVENT COORDINATOR" },
  // { name: "NIRMAL SINGH RATHOUR", course: "B.TECH ECE", year: "2nd Year", position: "DOCUMENTATION HEAD" },
  // { name: "ANISHA BORA", course: "B.TECH ECE", year: "2nd Year", position: "DOCUMENTATION HEAD" },
  // { name: "SHIVANSH NARAIN", course: "B.TECH ECE", year: "2nd Year", position: "PUBLICITY HEAD" },
  // { name: "RISHITA NAINWAL", course: "B.TECH CSE", year: "2nd Year", position: "PUBLICITY HEAD" },
  // { name: "KUMAR TEJAS", course: "B.TECH CSE", year: "1st Year", position: "PHOTOGRAPHY / VIDEOGRAPHY" },
  // { name: "ABHINAY PRATAP SINGH", course: "B.TECH CSE", year: "1st Year", position: "PHOTOGRAPHY / VIDEOGRAPHY" },
  // { name: "SAHIL RAWAT", course: "B.TECH CSE", year: "2nd Year", position: "SOCIAL MEDIA HEAD" },
  // { name: "IFRA MALIK", course: "B.TECH CSE", year: "2nd Year", position: "SOCIAL MEDIA HEAD" },
  // { name: "LAKSHIT PANDEY", course: "B.TECH CSE", year: "1st Year", position: "SOCIAL MEDIA" },
  // { name: "JYOTI JOSHI", course: "B.TECH CSE", year: "1st Year", position: "SOCIAL MEDIA" },
  // { name: "ANUJ JOSHI", course: "B.TECH CSE", year: "1st Year", position: "VOLUNTEER" },
  // { name: "AVANI JOSHI", course: "B.TECH CSE", year: "1st Year", position: "VOLUNTEER" },
  // { name: "DAKSH PATHAK", course: "B.TECH CSE", year: "1st Year", position: "VOLUNTEER" },
  // { name: "DEEPIKA PANT", course: "B.TECH CSE", year: "1st Year", position: "VOLUNTEER" },
  // { name: "GAURAV KANDPAL", course: "B.TECH CSE", year: "1st Year", position: "VOLUNTEER" },
  // { name: "GAURAV NEGI", course: "B.TECH CSE", year: "1st Year", position: "VOLUNTEER" },
  // { name: "HARSHIT BELAL", course: "B.TECH CSE", year: "1st Year", position: "VOLUNTEER" },
  // { name: "HARSHIT BISHT", course: "B.TECH CSE", year: "1st Year", position: "VOLUNTEER" },
  // { name: "JYOTI FULARA", course: "B.TECH CSE", year: "1st Year", position: "VOLUNTEER" },
  // { name: "KARTAVYA JOSHI", course: "B.TECH CSE", year: "1st Year", position: "VOLUNTEER" },
  // { name: "LOKESH SINGH", course: "B.TECH CSE", year: "1st Year", position: "VOLUNTEER" },
  // { name: "LOKESH SINGH GOSAIN", course: "B.TECH CSE", year: "1st Year", position: "VOLUNTEER" },
  // { name: "OM JOSHI", course: "B.TECH CSE", year: "1st Year", position: "VOLUNTEER" },
  // { name: "PAYAL TIWARI", course: "B.TECH CSE", year: "1st Year", position: "VOLUNTEER" },
  // { name: "PRAJWAL SURYA", course: "B.TECH CSE", year: "1st Year", position: "VOLUNTEER" },
  // { name: "RITESH BHATT", course: "B.TECH CSE", year: "1st Year", position: "VOLUNTEER" },
  // { name: "SAUMYA MEHRA", course: "B.TECH CSE", year: "1st Year", position: "VOLUNTEER" },
  // { name: "SONI GARIYA", course: "B.TECH CSE", year: "1st Year", position: "VOLUNTEER" },
  // { name: "SHUBHAM BOHRA", course: "B.TECH CSE", year: "1st Year", position: "VOLUNTEER" },
  // { name: "TANISHA BHATT", course: "B.TECH CSE", year: "1st Year", position: "VOLUNTEER" },
  // { name: "DIPANSHU PANDEY", course: "B.TECH CSE", year: "2nd Year", position: "VOLUNTEER" },
  // { name: "DIVYANSHI PAL", course: "B.TECH CSE", year: "2nd Year", position: "VOLUNTEER" },
  // { name: "PUSHPESH PANT", course: "B.TECH CSE", year: "2nd Year", position: "VOLUNTEER" },
  // { name: "RAHUL JOSHI", course: "B.TECH CSE", year: "2nd Year", position: "VOLUNTEER" },
  // { name: "SARVESH SUYAL", course: "B.TECH CSE", year: "2nd Year", position: "VOLUNTEER" },
  { name: "ABHINAY PRATAP SINGH", course: "B.TECH CSE", year: "1st Year", position: "Reveal by 31st December, 2025" },
  { name: "ANUJ JOSHI", course: "B.TECH CSE", year: "1st Year", position: "Reveal by 31st December, 2025" },
  { name: "ARYAN TIWARI", course: "B.TECH CSE", year: "1st Year", position: "Reveal by 31st December, 2025" },
  { name: "AVANI JOSHI", course: "B.TECH CSE", year: "1st Year", position: "Reveal by 31st December, 2025" },
  { name: "DAKSH PATHAK", course: "B.TECH CSE", year: "1st Year", position: "Reveal by 31st December, 2025" },
  { name: "DEEPIKA PANT", course: "B.TECH CSE", year: "1st Year", position: "Reveal by 31st December, 2025" },
  { name: "GAURAV KANDPAL", course: "B.TECH CSE", year: "1st Year", position: "Reveal by 31st December, 2025" },
  { name: "GAURAV NEGI", course: "B.TECH CSE", year: "1st Year", position: "Reveal by 31st December, 2025" },
  { name: "HARSH MAURYA", course: "B.TECH CSE", year: "1st Year", position: "Reveal by 31st December, 2025" },
  { name: "HARSHIT BELAL", course: "B.TECH CSE", year: "1st Year", position: "Reveal by 31st December, 2025" },
  { name: "HARSHIT BISHT", course: "B.TECH CSE", year: "1st Year", position: "Reveal by 31st December, 2025" },
  { name: "JYOTI FULARA", course: "B.TECH CSE", year: "1st Year", position: "Reveal by 31st December, 2025" },
  { name: "JYOTI JOSHI", course: "B.TECH CSE", year: "1st Year", position: "Reveal by 31st December, 2025" },
  { name: "KARTAVYA JOSHI", course: "B.TECH CSE", year: "1st Year", position: "Reveal by 31st December, 2025" },
  { name: "KUMAR TEJAS", course: "B.TECH CSE", year: "1st Year", position: "Reveal by 31st December, 2025" },
  { name: "LAKSHIT PANDEY", course: "B.TECH CSE", year: "1st Year", position: "Reveal by 31st December, 2025" },
  { name: "LOKESH SINGH", course: "B.TECH CSE", year: "1st Year", position: "Reveal by 31st December, 2025" },
  { name: "LOKESH SINGH GOSAIN", course: "B.TECH CSE", year: "1st Year", position: "Reveal by 31st December, 2025" },
  { name: "OM JOSHI", course: "B.TECH CSE", year: "1st Year", position: "Reveal by 31st December, 2025" },
  { name: "PAYAL TIWARI", course: "B.TECH CSE", year: "1st Year", position: "Reveal by 31st December, 2025" },
  { name: "PRAJWAL SURYA", course: "B.TECH CSE", year: "1st Year", position: "Reveal by 31st December, 2025" },
  { name: "PRIYANKA GANGWAR", course: "B.TECH CSE", year: "1st Year", position: "Reveal by 31st December, 2025" },
  { name: "RITESH BHATT", course: "B.TECH CSE", year: "1st Year", position: "Reveal by 31st December, 2025" },
  { name: "SAUMYA MEHRA", course: "B.TECH CSE", year: "1st Year", position: "Reveal by 31st December, 2025" },
  { name: "SHUBHAM BOHRA", course: "B.TECH CSE", year: "1st Year", position: "Reveal by 31st December, 2025" },
  { name: "SONI GARIYA", course: "B.TECH CSE", year: "1st Year", position: "Reveal by 31st December, 2025" },
  { name: "TANISHA BHATT", course: "B.TECH CSE", year: "1st Year", position: "Reveal by 31st December, 2025" },
  { name: "ANISHA BORA", course: "B.TECH ECE", year: "2nd Year", position: "Reveal by 31st December, 2025" },
  { name: "DIPANSHU PANDEY", course: "B.TECH CSE", year: "2nd Year", position: "Reveal by 31st December, 2025" },
  { name: "DIVYANSHI PAL", course: "B.TECH CSE", year: "2nd Year", position: "Reveal by 31st December, 2025" },
  { name: "HEMANT GOSWAMI", course: "B.TECH ECE", year: "2nd Year", position: "Reveal by 31st December, 2025" },
  { name: "HIMANSHI KARAKOTI", course: "B.TECH CSE", year: "2nd Year", position: "Reveal by 31st December, 2025" },
  { name: "IFRA MALIK", course: "B.TECH CSE", year: "2nd Year", position: "Reveal by 31st December, 2025" },
  { name: "KHUSHBU KANYAL", course: "B.TECH CSE", year: "2nd Year", position: "Reveal by 31st December, 2025" },
  { name: "NIRMAL SINGH RATHOUR", course: "B.TECH ECE", year: "2nd Year", position: "Reveal by 31st December, 2025" },
  { name: "NIRAJ SINGH BISHT", course: "B.TECH ECE", year: "2nd Year", position: "Reveal by 31st December, 2025" },
  { name: "PRATYUSH BAMETA", course: "B.TECH CSE", year: "2nd Year", position: "Reveal by 31st December, 2025" },
  { name: "PUSHPESH PANT", course: "B.TECH CSE", year: "2nd Year", position: "Reveal by 31st December, 2025" },
  { name: "RAHUL JOSHI", course: "B.TECH CSE", year: "2nd Year", position: "Reveal by 31st December, 2025" },
  { name: "RIYA BHATT", course: "B.TECH CSE", year: "2nd Year", position: "Reveal by 31st December, 2025" },
  { name: "RISHITA NAINWAL", course: "B.TECH CSE", year: "2nd Year", position: "Reveal by 31st December, 2025" },
  { name: "SAHIL RAWAT", course: "B.TECH CSE", year: "2nd Year", position: "Reveal by 31st December, 2025" },
  { name: "SAMARTH JOHRI", course: "B.TECH CSE", year: "2nd Year", position: "Reveal by 31st December, 2025" },
  { name: "SAMRIDDHI GURURANI", course: "B.TECH CSE", year: "2nd Year", position: "Reveal by 31st December, 2025" },
  { name: "SARVESH SUYAL", course: "B.TECH CSE", year: "2nd Year", position: "Reveal by 31st December, 2025" },
  { name: "SHIVANSH NARAIN", course: "B.TECH ECE", year: "2nd Year", position: "Reveal by 31st December, 2025" },
  { name: "SMITI SINGH", course: "B.TECH CSE", year: "2nd Year", position: "Reveal by 31st December, 2025" },
  { name: "VARUN SINGH", course: "B.TECH CSE", year: "2nd Year", position: "Reveal by 31st December, 2025" },
  { name: "VANSHIKA CHAUHAN", course: "BCA", year: "2nd Year", position: "Reveal by 31st December, 2025" },
  { name: "YASH KARKI", course: "B.TECH CSE", year: "2nd Year", position: "Reveal by 31st December, 2025" }
];